"""Copy and structure for the public /industries pages.

Healthcare, Real Estate and Education are the focus industries: they lead the
/industries page and each of their agents has its own detail page. The other
four markets keep a shorter card set. Everything here is marketing copy; the
agents named are the core agents retuned in each market's vocabulary, and
`base` names the core agent each one comes from.
"""


def _isvg(inner: str) -> str:
    return ('<svg viewBox="0 0 24 24" fill="none" stroke="#fff" stroke-width="1.9" '
            'stroke-linecap="round" stroke-linejoin="round">' + inner + "</svg>")


# Icons shared by several industries' agents.
IC_RADAR = _isvg('<circle cx="12" cy="8" r="4"/><path d="M4 21c0-4 4-6 8-6s8 2 8 6"/>')
IC_ANSWER = _isvg('<circle cx="11" cy="11" r="7"/><path d="m21 21-3.4-3.4"/><path d="M11 7.5l.9 2.1 2.1.9-2.1.9-.9 2.1-.9-2.1-2.1-.9 2.1-.9z"/>')
IC_VOICE = _isvg('<path d="M21 11.5a8.5 8.5 0 0 1-12.6 7.5L3 21l2-5.4A8.5 8.5 0 1 1 21 11.5z"/><path d="M9 11h.01M15 11h.01M8.8 14.2s1.3 1.3 3.2 1.3 3.2-1.3 3.2-1.3"/>')
IC_PIN = _isvg('<path d="M12 21s-7-4.5-7-10a7 7 0 0 1 14 0c0 5.5-7 10-7 10z"/><circle cx="12" cy="11" r="2.4"/>')
IC_SHIELD = _isvg('<path d="M12 3l7 3v5c0 4.5-3 7.6-7 9-4-1.4-7-4.5-7-9V6z"/><path d="M9 12l2 2 4-4"/>')
IC_BRIEF = _isvg('<path d="M4 4h16v12H7l-3 3z"/><path d="M8 9h8M8 12h5"/>')
IC_AUDIT = _isvg('<path d="M9 11l3 3 8-8"/><path d="M21 12v7a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11"/>')
IC_TREND = _isvg('<path d="M3 3v18h18"/><path d="M7 14l3.5-3.5 3 3 5-6"/>')
IC_COMMITTEE = _isvg('<circle cx="9" cy="8" r="3.2"/><path d="M3 20c0-3.3 2.7-5 6-5s6 1.7 6 5"/><path d="M17 8h4M19 6v4"/>')
IC_BUILDING = _isvg('<path d="M3 21h18"/><path d="M6 21V6a1 1 0 0 1 1-1h10a1 1 0 0 1 1 1v15"/><path d="M12 8v4M10 10h4"/><path d="M10 21v-4h4v4"/>')
IC_GAP = _isvg('<path d="M4 6h16M4 12h16M4 18h10"/><circle cx="18" cy="18" r="3"/>')

ENGINES = "ChatGPT · Gemini · Perplexity · AI Overviews"


def _out(*rows):
    return [{"t": t, "s": s, "w": w} for t, s, w in rows]


def build_industries(brand):
    name = brand["name"]
    industries = [
        # ── Healthcare ───────────────────────────────────────────────────────
        {
            "slug": "healthcare",
            "name": "Healthcare & Patient Growth",
            "short": "Healthcare",
            "featured": True,
            "accent": "#fb7185", "accent2": "#c084fc",
            "icon": _isvg('<path d="M12 20.3S3.6 14.6 3.6 8.8A4.4 4.4 0 0 1 12 6a4.4 4.4 0 0 1 8.4 2.8c0 5.8-8.4 11.5-8.4 11.5z"/><path d="M6.4 12h2l1.3-2.4L12 14l1.4-3 1 1h3"/>'),
            "eyebrow": "Industry · Healthcare · Patient growth",
            "headline": "Patients pick a clinic",
            "headline_ital": "before they pick up the phone.",
            "lead": (f"A patient’s first appointment is now with a search box. They look up symptoms, "
                     f"ask an AI which clinic is best nearby, read your reviews at midnight, and compare "
                     f"three practices before anyone rings reception. {name} watches that whole journey, "
                     f"across searches, AI answers, reviews and calls, for every location you run, and "
                     f"shows your team where you’re winning patients and where you’re quietly losing them."),
            "stats": [
                {"v": "4", "l": "AI answer engines watched"},
                {"v": "3", "l": "patient-voice sources in one view"},
                {"v": "24/7", "l": "visibility and reputation watch"},
            ],
            "segments": ["Multi-location clinics", "Hospitals & health systems", "Dental & DSOs",
                         "Dermatology & aesthetics", "Behavioural & mental health", "Urgent & primary care"],
            "challenge": ("Why patients end up", "somewhere else."),
            "pains": [
                {"t": "The first appointment is a search",
                 "d": "Patients research symptoms, treatments and doctors long before they call. If your expertise isn’t visible in that moment, the decision gets made without you."},
                {"t": "Every location fights its own battle",
                 "d": "Each clinic wins or loses its own ‘near me’ search. One stale phone number, wrong opening hours or thin review profile quietly sends patients to the practice down the road."},
                {"t": "AI has become the referral",
                 "d": "Ask an AI engine for the best clinic nearby and it names two or three. Not being named is the new not being listed."},
                {"t": "The truth is in the calls",
                 "d": "What patients really think lives in phone calls, reviews and surveys, scattered across tools nobody reads side by side. Problems show up as a falling rating, months too late."},
            ],
            "signals": ["Symptom & condition searches", "‘Near me’ and ‘best clinic’ queries",
                        "AI answers that cite you, or don’t", "New reviews by location", "Sentiment swings",
                        "Call volume & call topics", "A competitor opens nearby", "Service-line demand spikes",
                        "Rating drop at a location", "Survey & NPS movement"],
            "plays_h": ("From first search", "to booked appointment."),
            "plays": [
                {"t": "Own the local moment",
                 "d": "Win the symptom, treatment and near-me searches patients run, with every location accurate on Google Maps."},
                {"t": "Be the clinic AI names",
                 "d": "Earn the citation when a patient asks an AI engine about a symptom, a treatment or the best care nearby."},
                {"t": "Hear every patient",
                 "d": "Turn calls, reviews and surveys into a live sentiment score for each location, and fix the things patients keep mentioning."},
                {"t": "Content patients can trust",
                 "d": "Clinically reviewed, clearly credentialed pages that reassure patients and give AI engines a reason to cite you."},
            ],
            "cta_h": "Run it across your locations.",
            "cta_p": "Sign up, add your clinics, and see where patients are finding you, and where they aren’t.",
            "agents": [
                {"slug": "patient-answer-visibility", "name": "Patient-Answer Visibility",
                 "base": "Generative Search Visibility", "badge": "FLAGSHIP",
                 "accent": "#38bdf8", "accent2": "#22d3ee", "icon": IC_ANSWER,
                 "role": "AI Answer-Engine Tracking", "metric": ENGINES,
                 "use": "Shows how your clinics, doctors and treatments come up when patients ask AI engines for advice, and which rival gets named when you don’t.",
                 "summary": "Patients now ask an AI before they ask a GP. Patient-Answer Visibility shows whether your clinics, specialists and treatments are part of the answer, and who is being recommended in your place.",
                 "benefit": "You stop guessing about AI search. You see your share of the answers, the sources the engines trust, and the questions worth winning back first.",
                 "how": "It runs branded, treatment and near-me prompts across the major answer engines, records how often you’re named and in what context, maps the pages they cite, and lists the gaps to close.",
                 "who": "Marketing, SEO and content teams at clinics, hospital groups and specialist practices.",
                 "connects": ["AI engines", "Brand Radar", "Search Console", "Sheets"],
                 "out": _out(("Your share of AI answers", "Across the engines patients actually use.", 86),
                             ("The questions you’re losing", "Where a rival clinic is the answer.", 80),
                             ("The sources AI trusts", "So you know what to publish next.", 74))},
                {"slug": "call-sentiment-intelligence", "name": "Call & Sentiment Intelligence",
                 "base": "Voice-of-Customer Analytics", "badge": "NEW",
                 "accent": "#2dd4aa", "accent2": "#34d399", "icon": IC_VOICE,
                 "role": "Voice-of-Patient Sentiment", "metric": "Calls · reviews · surveys · per location",
                 "use": "Reads call transcripts, Google reviews and post-visit surveys together and gives every location a sentiment score, so you see where patients are happy and where trust is slipping.",
                 "summary": "Every patient conversation, finally in one place. Call & Sentiment Intelligence brings call transcripts, Google Business Profile reviews and surveys together and scores how patients feel about each location.",
                 "benefit": "Reputation becomes a number you can watch, not a rating you discover. You see which clinics patients love, which are slipping, and the specific reasons behind each.",
                 "how": "It takes in transcripts, review text and survey answers, tags each by sentiment, emotion and topic, then rolls them up into a score per location and tracks how it moves.",
                 "who": "Marketing, operations and patient-experience leads who look after several locations.",
                 "connects": ["Call platform", "Google Business Profile", "Surveys", "Sheets"],
                 "out": _out(("A sentiment score per location", "The sites that need attention rise first.", 92),
                             ("What’s behind it, in plain words", "The themes driving praise and complaints.", 84),
                             ("The verbatims worth reading", "Flagged calls and reviews, ready to act on.", 78))},
                {"slug": "location-facility-visibility", "name": "Location & Facility Visibility",
                 "base": "Local Visibility Builder + GBP QC",
                 "accent": "#34d399", "accent2": "#a3e635", "icon": IC_PIN,
                 "role": "Local & Maps Visibility", "metric": "GBP · hours · NAP · every location",
                 "use": "Keeps every clinic, hospital and pharmacy accurate on Google Business Profiles and maps, so each one wins its own near-me search.",
                 "summary": "A patient who finds the wrong opening hours doesn’t call to check. They go elsewhere. This keeps every location accurate and competitive in local search.",
                 "benefit": "No more patients lost to an old phone number or a missing category. Every location shows up correctly where people look first.",
                 "how": "It audits each location’s Google Business Profile for accuracy, hours, categories and name, address and phone consistency, flags what’s wrong, and runs quality checks across the whole network.",
                 "who": "Local SEO and operations teams running many locations.",
                 "connects": ["Google Business Profile", "Maps", "Sheets", "CRM"],
                 "out": _out(("Every location, checked", "Address, hours, categories and phone.", 90),
                             ("Problems flagged by site", "Before they cost you patients.", 80),
                             ("Network-wide consistency", "One view across every location.", 76))},
                {"slug": "clinical-authority-optimizer", "name": "Clinical Authority Optimizer",
                 "base": "Content Authority Optimizer",
                 "accent": "#f5a623", "accent2": "#fbbf24", "icon": IC_SHIELD,
                 "role": "Clinical Trust Signals", "metric": "Reviewers · credentials · citations · freshness",
                 "use": "Checks every clinical page for reviewer bylines, credentials, citations and freshness, so patients and AI engines can see the expertise behind it.",
                 "summary": "In healthcare, trust is what ranks. Clinical Authority Optimizer makes the expertise behind each page visible, so patients feel reassured and AI engines treat you as a source worth citing.",
                 "benefit": "Your clinicians’ expertise stops hiding in the footer. Each page shows who wrote it, who reviewed it and when.",
                 "how": "It reviews each clinical page for author credentials, medical-reviewer bylines, citations and the date of last review, then recommends the specific edits that strengthen trust.",
                 "who": "Content and SEO teams responsible for clinical accuracy.",
                 "connects": ["CMS", "Search Console", "Schema", "Sheets"],
                 "out": _out(("Trust gaps, page by page", "Bylines, credentials and citations checked.", 84),
                             ("The edits that fix them", "Specific and ready for your editors.", 80),
                             ("Pages due a clinical review", "So nothing goes quietly stale.", 72))},
                {"slug": "condition-treatment-brief-architect", "name": "Condition & Treatment Brief Architect",
                 "base": "Content Brief Generator",
                 "accent": "#e879f9", "accent2": "#c084fc", "icon": IC_BRIEF,
                 "role": "Patient-Question Briefs", "metric": "Condition · symptom · treatment · near-me",
                 "use": "Turns the questions patients really ask, in search and in AI, into ready-to-write briefs for condition, treatment and near-me pages.",
                 "summary": "Patients don’t search for service lines. They search for what’s wrong. This builds briefs around the questions they actually type and ask AI.",
                 "benefit": "Writers start from real patient demand, organised by service line, instead of a guess about what people want to read.",
                 "how": "It gathers the questions patients ask across search and AI engines, groups them by service line, and builds a structured brief with headings, questions to answer and sources to cite.",
                 "who": "Content strategists and writers building service-line pages.",
                 "connects": ["Search Console", "AI engines", "Semrush", "Sheets"],
                 "out": _out(("Briefs built on real questions", "What patients actually search.", 86),
                             ("Structured and ready to write", "Headings, questions and sources included.", 80),
                             ("Grouped by service line", "So every page has one clear job.", 74))},
                {"slug": "healthcare-site-geo-auditor", "name": "Healthcare Site & GEO Auditor",
                 "base": "SEO & GEO Audit", "badge": "NEW",
                 "accent": "#6366f1", "accent2": "#818cf8", "icon": IC_AUDIT,
                 "role": "Site Health & AI Readiness", "metric": "200+ checks · results in seconds",
                 "use": "Runs 200+ technical, on-page, structured-data and answer-engine checks, plus accessibility and trust checks, and returns a ranked fix list.",
                 "summary": "A full health check for a healthcare website: technical SEO, on-page, schema, AI-readiness, accessibility and trust, returned as one ranked fix list.",
                 "benefit": "The week-long manual audit becomes a prioritised list you get in seconds, with the fixes that matter most for patients at the top.",
                 "how": "It crawls the site, runs technical, on-page, structured-data and answer-engine checks alongside WCAG accessibility and trust signals, scores every issue by impact and writes the fix.",
                 "who": "SEO leads and web teams at healthcare organisations.",
                 "connects": ["Crawl", "Search Console", "Schema", "Sheets"],
                 "out": _out(("200+ checks, scored", "Technical, on-page, schema and AI readiness.", 92),
                             ("Accessibility and trust flags", "WCAG and trust signals included.", 82),
                             ("A ranked fix list", "Highest impact first, ready to ship.", 80))},
            ],
        },
        # ── Real estate ──────────────────────────────────────────────────────
        {
            "slug": "real-estate",
            "name": "Real Estate",
            "short": "Real Estate",
            "featured": True,
            "accent": "#f59e0b", "accent2": "#fb7185",
            "icon": _isvg('<path d="M3 11l9-7 9 7"/><path d="M5 10v10h14V10"/><path d="M10 20v-5h4v5"/>'),
            "eyebrow": "Industry · Real estate · Developers & brokerages",
            "headline": "Buyers tour forty homes online",
            "headline_ital": "before they visit one.",
            "lead": (f"Property decisions start months before a site visit: in portal searches, floor-plan "
                     f"revisits, payment-plan checks and late-night questions to AI. {name} spots the "
                     f"buyers, tenants and investors who are getting serious, keeps every project and "
                     f"office visible wherever people search, and puts the warmest enquiries at the top "
                     f"of your team’s list, so nobody has to call every lead to find the good ones."),
            "stats": [
                {"v": "26", "l": "buying-signal types"},
                {"v": "4", "l": "AI answer engines watched"},
                {"v": "24/7", "l": "project and office watch"},
            ],
            "segments": ["Residential developers", "Brokerages & agencies", "Commercial real estate",
                         "Property management", "Luxury & second homes", "Proptech & portals"],
            "challenge": ("Why good property leads", "go cold."),
            "pains": [
                {"t": "Intent is invisible until it’s too late",
                 "d": "A buyer looks at the same floor plan six times and checks the payment plan twice, then enquires with whoever answers first. The interest was there for weeks. Nobody could see it."},
                {"t": "Every enquiry looks the same",
                 "d": "Portal leads, form fills and missed calls land in one pile. Reps work them in order of arrival rather than seriousness, so the hottest buyer waits behind fifty browsers."},
                {"t": "Projects compete street by street",
                 "d": "Each project and sales office lives or dies in local search and maps. A launch page nobody can find is a launch nobody hears about."},
                {"t": "Buyers now ask AI where to live",
                 "d": "‘Best new two-bed apartments near the station’ is a question people put to AI engines now. If the answer names a rival’s project, yours never makes the shortlist."},
            ],
            "signals": ["Repeat floor-plan & price-page visits", "Payment-plan & mortgage-calculator use",
                        "Brochure & site-visit page views", "Portal enquiry spikes",
                        "A rival project launches nearby", "Price change at a competing project",
                        "Infrastructure news near a site", "Office expansion at target companies",
                        "Review & rating shifts by office", "AI answers that name your projects"],
            "plays_h": ("From first scroll", "to site visit."),
            "plays": [
                {"t": "Call the serious ones first",
                 "d": "Rank every enquiry and every returning visitor by intent, so the first call goes to the buyer closest to deciding."},
                {"t": "Win the local search",
                 "d": "Keep every project, sales office and site accurate and easy to find on maps and ‘near me’ searches."},
                {"t": "Get named by AI",
                 "d": "Earn the mention when buyers and tenants ask AI engines where to buy, rent or invest in your micro-market."},
                {"t": "Launch with a head start",
                 "d": "See rival launches and price moves early, and time your campaigns to the weeks buyers are comparing."},
            ],
            "cta_h": "Run it on your projects.",
            "cta_p": "Sign up, add your projects and offices, and see which buyers are getting serious.",
            "agents": [
                {"slug": "buyer-intent-radar", "name": "Buyer-Intent Radar",
                 "base": "Anonymous Website Visitors", "badge": "FLAGSHIP",
                 "accent": "#f59e0b", "accent2": "#fbbf24", "icon": IC_RADAR,
                 "role": "Serious-Buyer Detection", "metric": "Floor plans · price pages · repeat visits",
                 "use": "Reads how people move through your project pages, floor plans, price lists and payment plans, and flags the sessions that look like a buyer getting serious.",
                 "summary": "Not every visitor is a buyer, and not every enquiry is ready. Buyer-Intent Radar reads behaviour across your project pages and lifts the people showing real intent, repeat floor-plan views, price checks, brochure downloads, to the top of the list.",
                 "benefit": "Reps stop working leads in the order they arrived and start with the people most likely to book a site visit. The serious buyer no longer waits behind fifty browsers.",
                 "how": "Visits are stitched into sessions, each session is scored on depth, recency and the pages that signal intent, and known contacts and companies are matched where possible. Each one lands in your CRM as a plain-English note with a suggested next step.",
                 "who": "Sales, pre-sales and marketing teams at developers and brokerages.",
                 "connects": ["Your website", "GTM", "CRM", "Sheets"],
                 "out": _out(("Enquiries ranked by seriousness", "Highest intent at the top.", 92),
                             ("What they looked at", "Projects, units and pages, in order.", 82),
                             ("A suggested first line", "So the first call is a relevant one.", 76))},
                {"slug": "project-answer-visibility", "name": "Project-Answer Visibility",
                 "base": "Generative Search Visibility", "badge": "NEW",
                 "accent": "#38bdf8", "accent2": "#22d3ee", "icon": IC_ANSWER,
                 "role": "AI Answer-Engine Tracking", "metric": ENGINES,
                 "use": "Shows whether your projects, offices and brand are named when people ask AI engines where to buy, rent or invest, and which rival is named instead.",
                 "summary": "Buyers are asking AI to shortlist neighbourhoods and projects for them. Project-Answer Visibility shows whether your developments make that shortlist, and what the engines are reading when they don’t.",
                 "benefit": "You see the AI shortlist your buyers see, project by project, and the pages and listings you need to fix to get on it.",
                 "how": "It runs location, budget and project prompts across the major answer engines, records when you’re named and how you’re described, maps the sources being cited, and lists the gaps.",
                 "who": "Marketing and digital teams at developers, brokerages and property portals.",
                 "connects": ["AI engines", "Brand Radar", "Search Console", "Sheets"],
                 "out": _out(("Your share of AI shortlists", "Project by project, engine by engine.", 86),
                             ("Where rivals get named", "The questions you’re losing.", 80),
                             ("What the engines cite", "Listings and pages worth improving.", 72))},
                {"slug": "project-office-local-visibility", "name": "Project & Office Local Visibility",
                 "base": "Local Visibility Builder + GBP QC",
                 "accent": "#34d399", "accent2": "#a3e635", "icon": IC_PIN,
                 "role": "Local & Maps Visibility", "metric": "GBP · hours · NAP · every site",
                 "use": "Keeps every sales office, site and branch accurate on Google Business Profiles and maps, so people searching for new homes nearby find you, with the right number and hours.",
                 "summary": "A buyer driving past your site searches for it on their phone. This makes sure they find the right sales office, open at the right time, with a working number.",
                 "benefit": "Every project and office shows up properly in maps and local search, so walk-ins and calls go to you, not the developer across the road.",
                 "how": "It audits each site and office’s Google Business Profile for accuracy, hours, categories and contact details, flags inconsistencies, and checks the whole portfolio at once.",
                 "who": "Marketing and operations teams managing several projects or branches.",
                 "connects": ["Google Business Profile", "Maps", "Sheets", "CRM"],
                 "out": _out(("Every site and office, checked", "Address, hours, categories and phone.", 90),
                             ("Issues flagged by location", "Fixed before buyers notice.", 80),
                             ("One portfolio view", "Consistent across every project.", 74))},
                {"slug": "market-move-tracker", "name": "Market-Move Tracker",
                 "base": "ABM Signal Tracker", "badge": "CORE",
                 "accent": "#8b5cf6", "accent2": "#a78bfa", "icon": IC_TREND,
                 "role": "Market & Competitor Signals", "metric": "Launches · price moves · expansions",
                 "use": "Watches rival launches, price changes and infrastructure news near your sites and, for commercial teams, the funding and hiring surges that come before a company needs more space.",
                 "summary": "Real estate runs on timing. Market-Move Tracker watches the moves that change demand in your micro-markets, from a competing launch to a company that has just doubled its headcount.",
                 "benefit": "You hear about the rival launch, the price cut or the tenant outgrowing its office while there’s still time to act on it.",
                 "how": "It reads curated sources and open-web news for launches, price moves, infrastructure updates and company growth signals, scores each one by relevance and recency, and sends a weekly digest.",
                 "who": "Sales leaders, strategy teams and commercial leasing teams.",
                 "connects": ["Curated sources", "News", "Slack", "Sheets"],
                 "out": _out(("The moves that matter this week", "Ranked by relevance to your sites.", 90),
                             ("Why each one matters", "In one plain sentence.", 82),
                             ("Delivered to your team", "A weekly digest in Slack and Sheets.", 78))},
                {"slug": "enquiry-review-sentiment", "name": "Enquiry & Review Sentiment",
                 "base": "Voice-of-Customer Analytics",
                 "accent": "#2dd4aa", "accent2": "#34d399", "icon": IC_VOICE,
                 "role": "Voice-of-Buyer Sentiment", "metric": "Calls · reviews · surveys · per office",
                 "use": "Brings call transcripts, reviews and post-visit feedback into one sentiment score per office and project, so you know which sites delight buyers and which leak them.",
                 "summary": "Buyers tell you exactly why they didn’t book, on calls and in reviews. Enquiry & Review Sentiment collects all of it and scores how each office and project is really landing.",
                 "benefit": "You find the slow callbacks, confusing price sheets and unhappy site visits before they show up as lost sales.",
                 "how": "It takes in call transcripts, review text and feedback forms, tags each by sentiment and topic, and rolls the results up per office and project over time.",
                 "who": "Sales heads and customer-experience leads at developers and brokerages.",
                 "connects": ["Call platform", "Google Business Profile", "Surveys", "Sheets"],
                 "out": _out(("A score per office and project", "The ones slipping rise first.", 90),
                             ("The reasons, in plain words", "What buyers praise and what puts them off.", 82),
                             ("Calls worth listening to", "Flagged and ready for coaching.", 74))},
            ],
        },
        # ── Education ────────────────────────────────────────────────────────
        {
            "slug": "education",
            "name": "Education",
            "short": "Education",
            "featured": True,
            "accent": "#60a5fa", "accent2": "#a78bfa",
            "icon": _isvg('<path d="M2 9l10-5 10 5-10 5z"/><path d="M6 11v5c0 1.7 2.7 3 6 3s6-1.3 6-3v-5"/><path d="M22 9v6"/>'),
            "eyebrow": "Industry · Schools, colleges & universities",
            "headline": "Applicants decide",
            "headline_ital": "long before open day.",
            "lead": (f"A student’s shortlist is built in search results, AI answers, review sites and "
                     f"programme pages, often with a parent reading over their shoulder. {name} shows you "
                     f"which programmes are being found, whether AI recommends you, which visitors are "
                     f"getting serious about applying, and what students and parents really say, so "
                     f"admissions spends its time on the families most likely to enrol."),
            "stats": [
                {"v": "4", "l": "AI answer engines watched"},
                {"v": "3", "l": "student-voice sources in one view"},
                {"v": "24/7", "l": "programme and campus watch"},
            ],
            "segments": ["Universities", "Colleges & polytechnics", "K-12 & private schools",
                         "Online & executive programmes", "Coaching & test prep", "International admissions"],
            "challenge": ("Why great programmes", "go unchosen."),
            "pains": [
                {"t": "The shortlist forms in silence",
                 "d": "Students compare fees, rankings and placement pages for months without filling in an enquiry form. By the time they do, the shortlist is usually three names long."},
                {"t": "AI is the new careers counsellor",
                 "d": "‘Best data-science course with placements near me’ is a question students ask AI now. The institutions it names start the race in front."},
                {"t": "Every programme has its own buyer",
                 "d": "An MBA, a nursing diploma and a Year 7 place are chosen by completely different people for completely different reasons. One generic campaign speaks to none of them."},
                {"t": "Students and parents set your reputation",
                 "d": "Reviews, forum threads and calls to admissions shape perception far more than the prospectus does, and nobody reads them all together."},
            ],
            "signals": ["Programme & fee-page revisits", "Eligibility & application-page views",
                        "Scholarship & placement-page interest", "Open-day & campus-tour page visits",
                        "Course & ‘near me’ searches", "AI answers that name your institution",
                        "A rival launches a programme", "Ranking & accreditation news",
                        "Review & rating shifts by campus", "Admissions-call topics & sentiment"],
            "plays_h": ("From first search", "to first day of term."),
            "plays": [
                {"t": "Follow up with the serious ones",
                 "d": "Rank enquiries and returning visitors by intent, so counsellors call the families closest to applying."},
                {"t": "Be the name AI recommends",
                 "d": "Earn the mention when students and parents ask AI engines for the best programme or school for them."},
                {"t": "One page per decision",
                 "d": "Build programme and admissions pages that answer the exact questions applicants and parents search for."},
                {"t": "Listen at scale",
                 "d": "Turn admissions calls, reviews and surveys into a live read on reputation, campus by campus."},
            ],
            "cta_h": "Run it on your next intake.",
            "cta_p": "Sign up, add your programmes and campuses, and see which applicants are getting serious.",
            "agents": [
                {"slug": "applicant-intent-radar", "name": "Applicant-Intent Radar",
                 "base": "Anonymous Website Visitors", "badge": "FLAGSHIP",
                 "accent": "#60a5fa", "accent2": "#38bdf8", "icon": IC_RADAR,
                 "role": "Serious-Applicant Detection", "metric": "Programmes · fees · eligibility · apply",
                 "use": "Reads how visitors move through programme, fee, eligibility and application pages, and flags the sessions that look like someone about to apply.",
                 "summary": "Most applicants research quietly for months. Applicant-Intent Radar reads behaviour across your programme and admissions pages and lifts the visitors showing real intent to the top of your counsellors’ list.",
                 "benefit": "Admissions stops chasing every enquiry equally and starts with the students closest to applying, while they’re still deciding.",
                 "how": "Visits are stitched into sessions and scored on depth, recency and the pages that signal intent, such as fees, eligibility and the application form. Known contacts are matched where possible and each lead reaches your CRM with a suggested next step.",
                 "who": "Admissions, enrolment-marketing and counselling teams.",
                 "connects": ["Your website", "GTM", "CRM", "Sheets"],
                 "out": _out(("Applicants ranked by intent", "Closest to applying at the top.", 92),
                             ("The programmes they’re weighing", "Pages read, in order.", 82),
                             ("A suggested next step", "So the follow-up feels personal.", 76))},
                {"slug": "programme-answer-visibility", "name": "Programme-Answer Visibility",
                 "base": "Generative Search Visibility", "badge": "NEW",
                 "accent": "#38bdf8", "accent2": "#22d3ee", "icon": IC_ANSWER,
                 "role": "AI Answer-Engine Tracking", "metric": ENGINES,
                 "use": "Shows whether your institution and programmes are named when students and parents ask AI engines for the best course, college or school, and who is named instead.",
                 "summary": "‘Which college is best for…’ is now a question for AI. Programme-Answer Visibility shows when your institution is in the answer, how it’s described, and which rivals are taking your place.",
                 "benefit": "You see the AI shortlist applicants see, programme by programme, and know exactly which pages to strengthen to get on it.",
                 "how": "It runs programme, location and career-outcome prompts across the major answer engines, records how often you’re named and in what terms, maps the cited sources, and lists the gaps.",
                 "who": "Marketing, digital and admissions teams at schools, colleges and universities.",
                 "connects": ["AI engines", "Brand Radar", "Search Console", "Sheets"],
                 "out": _out(("Your share of AI recommendations", "Per programme, per engine.", 86),
                             ("Where rivals get named", "The questions you’re losing.", 80),
                             ("The sources AI trusts", "Rankings, reviews and pages to improve.", 72))},
                {"slug": "programme-brief-architect", "name": "Programme Page Brief Architect",
                 "base": "Content Brief Generator",
                 "accent": "#e879f9", "accent2": "#c084fc", "icon": IC_BRIEF,
                 "role": "Applicant-Question Briefs", "metric": "Programmes · admissions · careers · fees",
                 "use": "Turns the questions students and parents really search and ask AI into ready-to-write briefs for programme, admissions and career-outcome pages.",
                 "summary": "Applicants want to know about fees, placements, eligibility and what life is like. This builds page briefs around the questions they actually ask.",
                 "benefit": "Programme pages that answer the real questions convert better, rank better and get cited by AI more often.",
                 "how": "It gathers the questions applicants and parents ask across search and AI engines, groups them by programme, and builds a structured brief with headings, questions to answer and sources.",
                 "who": "Content and marketing teams writing programme and admissions pages.",
                 "connects": ["Search Console", "AI engines", "Semrush", "Sheets"],
                 "out": _out(("Briefs built on real questions", "What applicants actually search.", 86),
                             ("Structured and ready to write", "Headings, questions and sources.", 80),
                             ("One brief per programme", "So every page has one clear job.", 74))},
                {"slug": "campus-local-visibility", "name": "Campus Local Visibility",
                 "base": "Local Visibility Builder + GBP QC",
                 "accent": "#34d399", "accent2": "#a3e635", "icon": IC_PIN,
                 "role": "Local & Maps Visibility", "metric": "GBP · hours · NAP · every campus",
                 "use": "Keeps every campus, admissions office and study centre accurate on Google Business Profiles and maps, so families searching nearby find the right door.",
                 "summary": "Parents searching for schools nearby decide from the map. This keeps every campus and admissions office accurate, complete and easy to find.",
                 "benefit": "Open-day visitors find the right building, enquiries reach the right office, and no campus loses families to an out-of-date listing.",
                 "how": "It audits each campus and office’s Google Business Profile for accuracy, hours, categories and contact details, flags problems, and checks every location at once.",
                 "who": "Marketing and operations teams at multi-campus institutions and school groups.",
                 "connects": ["Google Business Profile", "Maps", "Sheets", "CRM"],
                 "out": _out(("Every campus, checked", "Address, hours, categories and phone.", 90),
                             ("Issues flagged by location", "Fixed before open day.", 80),
                             ("One view across campuses", "Consistent everywhere families look.", 74))},
                {"slug": "student-parent-sentiment", "name": "Student & Parent Sentiment",
                 "base": "Voice-of-Customer Analytics",
                 "accent": "#2dd4aa", "accent2": "#34d399", "icon": IC_VOICE,
                 "role": "Voice-of-Student Sentiment", "metric": "Calls · reviews · surveys · per campus",
                 "use": "Combines admissions calls, reviews and surveys into a sentiment score per campus and programme, so you know what families praise and what keeps worrying them.",
                 "summary": "Families tell admissions exactly what they’re unsure about. Student & Parent Sentiment collects those conversations, with reviews and surveys, and turns them into a clear read on reputation.",
                 "benefit": "You hear the recurring worries, about fees, safety, placements or hostels, early enough to answer them on the website and on the phone.",
                 "how": "It takes in call transcripts, review text and survey answers, tags each by sentiment and topic, and rolls the results up by campus and programme over time.",
                 "who": "Admissions heads, student-experience and marketing leaders.",
                 "connects": ["Call platform", "Google Business Profile", "Surveys", "Sheets"],
                 "out": _out(("A score per campus and programme", "The ones slipping rise first.", 90),
                             ("The worries, in plain words", "What families ask about most.", 82),
                             ("Calls worth hearing", "Flagged for training and follow-up.", 74))},
            ],
        },
        # ── Health tech (B2B) ────────────────────────────────────────────────
        {
            "slug": "health-tech",
            "name": "Health Tech",
            "short": "Health Tech",
            "featured": False,
            "accent": "#22d3ee", "accent2": "#34d399",
            "icon": _isvg('<path d="M3 12h3.5l2 5 4-12 2.2 7H21"/>'),
            "eyebrow": "Industry · Health tech",
            "headline": "Health systems buy slowly.",
            "headline_ital": "They signal early.",
            "lead": (f"Selling into healthcare means long cycles, big committees and buyers who trust "
                     f"peers more than pitches. But health systems telegraph their next move: a merger, a "
                     f"new facility, a new CMIO, a fresh round of funding. {name} watches providers, payers, "
                     f"digital-health and medtech organisations for those moves, and gives your team the "
                     f"account, the committee and a reason to call."),
            "stats": [
                {"v": "50", "l": "most-active health organisations tracked"},
                {"v": "26", "l": "buying-signal types"},
                {"v": "24/7", "l": "signal detection"},
            ],
            "segments": ["Digital health & telehealth", "Medtech & devices", "Health IT & EHR",
                         "Payers & health plans", "Pharma & biotech", "Revenue-cycle vendors"],
            "pains": [
                {"t": "Ten people sign every deal",
                 "d": "One purchase touches the CMIO, CNIO, CFO, service-line leaders and procurement. You need to know which system is in-market, and who sits on the committee, before a competitor does."},
                {"t": "The budget clues are scattered",
                 "d": "Funding, mergers, new facilities, regulatory changes and leadership moves all come before spend, but they’re spread across filings, news and job boards."},
                {"t": "Shortlists are built on trust",
                 "d": "Buyers check peers, analysts and now AI engines before they talk to vendors. If you aren’t the name that comes up, you aren’t in the evaluation."},
                {"t": "The research happens quietly",
                 "d": "Health systems study your site for weeks without filling in a form. That quiet attention is the warmest pipeline you have."},
            ],
            "signals": ["Funding round", "Health-system merger or acquisition", "New facility or clinic",
                        "Service-line launch", "CMIO, CNIO or C-suite change", "FDA clearance or approval",
                        "Clinical-trial milestone", "Clinical & tech hiring surge",
                        "Payer–provider partnership", "Earnings & regulatory filings"],
            "plays": [
                {"t": "Account-based demand",
                 "d": "Launch campaigns at in-market systems and payers the week a funding, expansion or leadership signal fires, within healthcare ad policy."},
                {"t": "Committee mapping",
                 "d": "Know the clinical, finance and procurement people at every target, and hear when a champion moves."},
                {"t": "Category authority",
                 "d": "Win the searches and AI answers buyers read while building a shortlist."},
                {"t": "Routing and follow-through",
                 "d": "One intent score per account, explained in a sentence and routed with a suggested opener into HubSpot, Salesforce and Slack."},
            ],
            "agents": [
                {"slug": "health-tech-account-tracker", "name": "Health-Tech Account Tracker",
                 "base": "ABM Signal Tracker", "badge": "LIVE",
                 "accent": "#22d3ee", "accent2": "#38bdf8", "icon": IC_BUILDING,
                 "role": "Ready-Made Health-Tech Universe", "metric": "50 most-active organisations · ranked weekly",
                 "use": "A health-tech target list that’s already live: the 50 most-active provider, payer, digital-health and medtech organisations, watched for funding, leadership moves, M&A and news.",
                 "summary": "Skip the list-building. Health-Tech Account Tracker arrives preloaded with the 50 most-active provider, payer, digital-health and medtech organisations, watched for the moves that come before a budget.",
                 "benefit": "Nothing to configure. From day one you have a ranked view of the healthcare organisations most likely to be starting a buying cycle.",
                 "how": "It monitors funding, M&A, leadership changes, facility openings and news across the tracked organisations, scores each event and refreshes the ranking every week.",
                 "who": "Sales and demand-gen teams selling to health systems, payers and healthcare vendors.",
                 "connects": ["Curated sources", "News", "Slack", "Sheets"],
                 "out": _out(("50 organisations, ready to work", "Preloaded and refreshed weekly.", 95),
                             ("The ones moving, on top", "Ranked by live intent.", 88),
                             ("A weekly digest", "Straight to Slack and Sheets.", 80))},
                {"slug": "provider-payer-signal-tracker", "name": "Provider & Payer Signal Tracker",
                 "base": "ABM Signal Tracker", "badge": "CORE",
                 "accent": "#8b5cf6", "accent2": "#a78bfa", "icon": IC_TREND,
                 "role": "Account Intent Monitoring", "metric": "26 signal types · ranked weekly",
                 "use": "Watches your own list of health systems, payers and vendors for funding, mergers, facility openings and leadership moves, and re-ranks them every week.",
                 "summary": "Point it at your own target list of health systems, payers, digital-health and medtech accounts, and the ones starting to move float to the top on their own.",
                 "benefit": "You hear about the expansion, the new CFO or the merger in the week it happens, without anyone scrubbing a spreadsheet.",
                 "how": "It reads curated healthcare sources and open-web news, scores each event by type, severity and recency, keeps a rolling 90-day memory and sends a weekly digest.",
                 "who": "Demand-gen and sales teams running account-based programmes in healthcare.",
                 "connects": ["Curated sources", "News", "Slack", "Sheets"],
                 "out": _out(("The accounts moving most", "Ranked by impact, newest first.", 94),
                             ("Why each one matters", "The signal, in one sentence.", 82),
                             ("Routed to your team", "A weekly digest in Slack and Sheets.", 80))},
                {"slug": "buying-committee-tracker", "name": "Buying-Committee Tracker",
                 "base": "LinkedIn Intelligence",
                 "accent": "#818cf8", "accent2": "#6366f1", "icon": IC_COMMITTEE,
                 "role": "People & Committee Mapping", "metric": "CMIO · CNIO · revenue cycle · procurement",
                 "use": "Maps the committee inside each target health system, follows job changes and engagement, and tells you when a champion moves or leans in.",
                 "summary": "Healthcare deals are won person by person. Buying-Committee Tracker maps who sits on the committee at each target and tells you when one of them moves or starts paying attention.",
                 "benefit": "You re-engage the right person at the right moment instead of emailing a generic inbox.",
                 "how": "It maps roles such as CMIO, CNIO, VP of revenue cycle and procurement at each target system, follows job changes and engagement, and surfaces champions as they move.",
                 "who": "Sales and ABM teams selling into health systems.",
                 "connects": ["LinkedIn", "Apollo", "CRM", "Sheets"],
                 "out": _out(("The committee, mapped", "Roles and decision-makers per system.", 86),
                             ("Job changes, caught", "A champion who moves is a warm lead.", 80),
                             ("Who’s paying attention", "And when they started.", 74))},
                {"slug": "buyer-referrer-de-anonymization", "name": "Buyer & Referrer Identification",
                 "base": "Anonymous Website Visitors", "badge": "NEW",
                 "accent": "#34d399", "accent2": "#2dd4aa", "icon": IC_RADAR,
                 "role": "Visitor Identification", "metric": "Names the organisations behind silent traffic",
                 "use": "Names the health systems, referring clinics and employer groups reading your site, even when they never fill in a form, and shows the pages they read.",
                 "summary": "Most of the health systems researching you never say hello. This names the organisations behind that quiet traffic and tells your team what they were reading.",
                 "benefit": "Reach the organisations already evaluating you while their interest is still warm.",
                 "how": "Visits are matched to company identity, each session is rebuilt page by page, and every visitor becomes a plain-English note with a suggested next step.",
                 "who": "Website, demand-gen and outreach teams.",
                 "connects": ["Your website", "GTM", "CRM", "Sheets"],
                 "out": _out(("The organisations on your site", "Named, no form required.", 90),
                             ("The pages they read", "Rebuilt session by session.", 78),
                             ("A suggested opener", "So reps act while it’s warm.", 74))},
            ],
        },
        # ── Technology & SaaS ────────────────────────────────────────────────
        {
            "slug": "technology-saas",
            "name": "Technology & SaaS",
            "short": "Technology & SaaS",
            "featured": False,
            "accent": "#818cf8", "accent2": "#22d3ee",
            "icon": _isvg('<rect x="3" y="4" width="18" height="13" rx="2"/><path d="M8 21h8M12 17v4"/><path d="M8 9l2.2 2L8 13M14 9h2.5"/>'),
            "eyebrow": "Industry · Technology & SaaS",
            "headline": "The demo request",
            "headline_ital": "is the last step, not the first.",
            "lead": (f"Software buyers are three vendors deep before they book a demo. The real start "
                     f"was weeks earlier: a funding round, a new VP, a stack change, a burst of hiring, a "
                     f"quiet afternoon on your pricing page. {name} watches for all of it across your "
                     f"target accounts and tells your team who’s in a cycle, and why."),
            "stats": [
                {"v": "26", "l": "buying-signal types"},
                {"v": "4", "l": "AI answer engines watched"},
                {"v": "24/7", "l": "signal detection"},
            ],
            "segments": ["B2B SaaS", "Cloud & infrastructure", "Dev tools & APIs", "Cybersecurity",
                         "Data & AI", "Fintech software"],
            "pains": [
                {"t": "By the form fill, you’re late",
                 "d": "Accounts that request a demo have usually compared you already. The signal that mattered fired weeks before."},
                {"t": "AI writes the shortlist",
                 "d": "Buyers ask ChatGPT and Perplexity which tools to consider. If you aren’t in that answer, you aren’t on the list."},
                {"t": "Champions change jobs",
                 "d": "When your best champion leaves, the deal stalls. When they land somewhere new, that’s your warmest lead of the quarter."},
            ],
            "signals": ["Funding round", "Tech-stack change", "Engineering & GTM hiring surge",
                        "Product launch", "Leadership change", "M&A", "Partnership", "Earnings & filings"],
            "agents": [
                {"name": "Tech-Stack Signal Tracker", "base": "ABM Signal Tracker", "badge": "CORE", "icon": IC_TREND,
                 "use": "Watches funding, stack changes, hiring surges and launches across your target accounts and re-ranks them weekly, so the ones entering a software cycle surface first."},
                {"name": "AI Shortlist Visibility", "base": "Generative Search Visibility", "badge": "FLAGSHIP", "icon": IC_ANSWER,
                 "use": "Shows whether you’re named when buyers ask AI engines for the best tools in your category, and which comparison questions you’re losing."},
                {"name": "Pricing-Page Visitor ID", "base": "Anonymous Website Visitors", "badge": "NEW", "icon": IC_RADAR,
                 "use": "Names the companies reading your pricing and docs pages, so SDRs reach them while the evaluation is still open."},
                {"name": "Category Gap Finder", "base": "Competitor Analysis", "icon": IC_GAP,
                 "use": "Shows where rivals win organic and AI visibility in your category, and the keyword and content gaps worth closing first."},
                {"name": "Champion Tracker", "base": "LinkedIn Intelligence", "icon": IC_COMMITTEE,
                 "use": "Follows your champions when they change jobs and maps the buying committee at each target account."},
            ],
            "plays": [
                {"t": "Own the category answer", "d": "Win the searches and AI answers buyers use to build their shortlist."},
                {"t": "Spend where intent is", "d": "Target accounts the week their intent spikes, not a list from last quarter."},
                {"t": "Content for the comparison", "d": "Comparison, integration and use-case pages built around what buyers are evaluating right now."},
                {"t": "Clean handoffs", "d": "Score and route signals into the CRM so SDRs get context, not just a name."},
            ],
        },
        # ── Financial services ───────────────────────────────────────────────
        {
            "slug": "financial-services",
            "name": "Financial Services",
            "short": "Financial Services",
            "featured": False,
            "accent": "#34d399", "accent2": "#0ea5e9",
            "icon": _isvg('<path d="M3 21h18"/><path d="M5 21V9l7-5 7 5v12"/><path d="M9 21v-6h6v6"/>'),
            "eyebrow": "Industry · Financial services",
            "headline": "Big decisions, narrow windows.",
            "headline_ital": "Be first through them.",
            "lead": (f"In banking, insurance, fintech and wealth, deals are large, cycles are regulated and "
                     f"trust is the product. The openings come with change: a merger, a new chief risk "
                     f"officer, a new market. {name} catches those moments as they happen and keeps your "
                     f"visibility credible where buyers and AI engines look."),
            "stats": [
                {"v": "26", "l": "buying-signal types"},
                {"v": "4", "l": "AI answer engines watched"},
                {"v": "24/7", "l": "signal detection"},
            ],
            "segments": ["Banking", "Fintech & payments", "Insurance", "Wealth & asset management",
                         "Lending", "Insurtech"],
            "pains": [
                {"t": "Credibility is checked first",
                 "d": "Money content is held to a higher bar. Search engines and AI answers look hard at authority, accuracy and credentials before they surface you."},
                {"t": "Many voices, one decision",
                 "d": "Risk, compliance, finance and the business line all weigh in. You need to know which institution is moving, and who to talk to."},
                {"t": "Change redraws the map",
                 "d": "Mergers, new leaders and fresh funding change who buys what, and open a short window for whoever arrives first."},
            ],
            "signals": ["M&A & consolidation", "Funding round", "C-suite change", "New product or market",
                        "Regulatory filing", "Hiring surge", "Partnership", "Earnings & filings"],
            "agents": [
                {"name": "Institution Signal Tracker", "base": "ABM Signal Tracker", "badge": "CORE", "icon": IC_TREND,
                 "use": "Follows M&A, leadership changes, funding and expansion across banks, insurers and fintechs, re-ranked weekly so the institutions on the move rise first."},
                {"name": "Trusted-Answer Visibility", "base": "Generative Search Visibility", "badge": "FLAGSHIP", "icon": IC_ANSWER,
                 "use": "Shows how your brand appears in AI answers to high-stakes money questions, where authority decides who gets cited."},
                {"name": "Credibility Optimizer", "base": "Content Authority Optimizer", "icon": IC_SHIELD,
                 "use": "Strengthens the credentials, citations and disclosures that finance content needs before search engines and AI will trust it."},
                {"name": "Institution Visitor ID", "base": "Anonymous Website Visitors", "badge": "NEW", "icon": IC_RADAR,
                 "use": "Names the institutions researching your solutions, so relationship teams reach them while interest is high."},
                {"name": "Stakeholder Mapper", "base": "LinkedIn Intelligence", "icon": IC_COMMITTEE,
                 "use": "Maps risk, compliance and business-line stakeholders, and flags the leadership moves that open a new relationship."},
            ],
            "plays": [
                {"t": "Credible visibility", "d": "Be the trusted, cited answer for the high-stakes questions buyers and AI engines ask."},
                {"t": "Targeted reach", "d": "Reach institutions on the move, within financial advertising rules."},
                {"t": "Content that passes review", "d": "Credentialed content that earns trust, citations and compliance sign-off."},
                {"t": "Context for relationship managers", "d": "Route each signal to the right relationship manager with the full story."},
            ],
        },
        # ── Professional services ────────────────────────────────────────────
        {
            "slug": "professional-services",
            "name": "Professional Services",
            "short": "Professional Services",
            "featured": False,
            "accent": "#fbbf24", "accent2": "#e879f9",
            "icon": _isvg('<path d="M6 7V5a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v2"/><rect x="3" y="7" width="18" height="13" rx="2"/><path d="M3 12h18"/>'),
            "eyebrow": "Industry · Professional services",
            "headline": "Change creates the brief.",
            "headline_ital": "Arrive with the answer.",
            "lead": (f"Consultancies, law firms, accountants and agencies are hired in moments of change: a "
                     f"round, a merger, a new general counsel, a new office. {name} spots those moments "
                     f"across your target accounts and gives your partners a timely, specific reason to get "
                     f"in touch first."),
            "stats": [
                {"v": "26", "l": "buying-signal types"},
                {"v": "4", "l": "AI answer engines watched"},
                {"v": "24/7", "l": "signal detection"},
            ],
            "segments": ["Management consulting", "Legal", "Accounting & advisory",
                         "Marketing & creative agencies", "Staffing & recruitment", "IT services"],
            "pains": [
                {"t": "Work comes through people",
                 "d": "Your pipeline runs on partners calling the right person at the right time, not on inbound forms. You need the trigger and the name."},
                {"t": "Expertise is hard to find",
                 "d": "Buyers and AI engines reward visible authority. Your best thinking has to be findable and quotable."},
                {"t": "The window is short",
                 "d": "A round, a merger or a new general counsel creates a brief, urgent need. The first credible firm in usually keeps it."},
            ],
            "signals": ["Funding round", "M&A", "C-suite change", "New office or expansion", "Hiring surge",
                        "Regulatory or legal event", "Partnership", "Earnings & filings"],
            "agents": [
                {"name": "Opportunity Signal Tracker", "base": "ABM Signal Tracker", "badge": "CORE", "icon": IC_TREND,
                 "use": "Spots growth, M&A, leadership and expansion moves across your target accounts, re-ranked weekly so partners see who needs help now."},
                {"name": "Expertise-Answer Visibility", "base": "Generative Search Visibility", "badge": "FLAGSHIP", "icon": IC_ANSWER,
                 "use": "Shows whether your firm is named when prospects ask AI engines for help in your practice areas."},
                {"name": "Insight-Reader ID", "base": "Anonymous Website Visitors", "badge": "NEW", "icon": IC_RADAR,
                 "use": "Names the companies reading your service and insight pages, so partners follow up while the need is fresh."},
                {"name": "Thought-Leadership Brief Architect", "base": "Content Brief Generator", "icon": IC_BRIEF,
                 "use": "Builds briefs around the questions buyers and AI engines ask in your practice areas, so your insight pieces get found and quoted."},
                {"name": "Relationship Mover Tracker", "base": "LinkedIn Intelligence", "icon": IC_COMMITTEE,
                 "use": "Tells you when key contacts change roles and maps the decision-makers at each target account."},
            ],
            "plays": [
                {"t": "Be the quoted expert", "d": "Make your practice-area expertise the answer buyers and AI engines find first."},
                {"t": "Reach the moment", "d": "Target accounts showing change, with partner-led messages that fit the moment."},
                {"t": "Insight that travels", "d": "Turn partner expertise into thought leadership people can find and quote."},
                {"t": "The right partner, fast", "d": "Route each signal to the partner best placed to act, with the context to do it well."},
            ],
        },
    ]
    for ind in industries:
        # The agent-count stat always matches the agents actually listed.
        ind["stats"].append({"v": str(len(ind["agents"])),
                             "l": "agents tuned for %s" % ind["short"].lower()})
    return industries
