import { useMemo } from 'react';
import { useSearchParams, useNavigate } from 'react-router-dom';

export default function AgentReadinessSummaryPage() {
  const [searchParams] = useSearchParams();
  const navigate = useNavigate();
  const d = searchParams.get('d');

  const data = useMemo(() => {
    if (!d) return null;
    try { return JSON.parse(atob(d)); } catch { return null; }
  }, [d]);

  if (!data) return (
    <div style={{ minHeight: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center', fontFamily: 'system-ui, sans-serif' }}>
      <div style={{ textAlign: 'center' }}>
        <p style={{ color: '#6B7280' }}>Invalid or missing summary data.</p>
        <button onClick={() => navigate('/agent-readiness-audit')} style={{ marginTop: 12, fontSize: 13, color: '#534AB7', background: 'none', border: 'none', cursor: 'pointer', textDecoration: 'underline' }}>Run a new audit →</button>
      </div>
    </div>
  );

  const { brief, url, full, score, level, date } = data;
  const scoreColor = score >= 70 ? '#639922' : score >= 40 ? '#EF9F27' : '#E24B4A';

  return (
    <div style={{ minHeight: '100vh', background: '#F4F5F7', fontFamily: 'system-ui, sans-serif', padding: '40px 20px' }}>
      <div style={{ maxWidth: 680, margin: '0 auto' }}>
        {/* Header */}
        <div style={{ background: '#fff', borderRadius: 12, border: '0.5px solid #E5E7EB', padding: '20px 24px', marginBottom: 16, boxShadow: '0 1px 3px rgba(0,0,0,0.07)' }}>
          <div style={{ fontSize: 10, color: '#9CA3AF', textTransform: 'uppercase', letterSpacing: '0.08em', marginBottom: 6 }}>Agent Readiness Audit</div>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
            <div>
              <h1 style={{ fontSize: 20, fontWeight: 500, margin: '0 0 4px', color: '#111827' }}>{url}</h1>
              <div style={{ fontSize: 13, color: '#6B7280' }}>{level} &nbsp;·&nbsp; Scanned {date}</div>
            </div>
            <div style={{ textAlign: 'right' }}>
              <div style={{ fontSize: 32, fontWeight: 600, color: scoreColor, lineHeight: 1 }}>{score}</div>
              <div style={{ fontSize: 11, color: '#9CA3AF' }}>out of 100</div>
            </div>
          </div>
        </div>

        {/* Executive Summary */}
        <div style={{ background: '#fff', borderRadius: 12, border: '0.5px solid #E5E7EB', padding: '20px 24px', marginBottom: 16, boxShadow: '0 1px 3px rgba(0,0,0,0.07)' }}>
          <div style={{ fontSize: 11, fontWeight: 600, color: '#534AB7', textTransform: 'uppercase', letterSpacing: '0.08em', marginBottom: 14 }}>✦ Executive Summary</div>
          <p style={{ fontSize: 17, fontWeight: 500, color: '#111827', margin: '0 0 10px', lineHeight: 1.4 }}>{brief.headline}</p>
          <p style={{ fontSize: 13, color: '#6B7280', margin: '0 0 16px', lineHeight: 1.7 }}>{brief.summary}</p>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(160px, 1fr))', gap: 10 }}>
            <div style={{ background: '#FCEBEB', borderRadius: 8, padding: '10px 12px' }}>
              <div style={{ fontSize: 10, fontWeight: 600, color: '#A32D2D', textTransform: 'uppercase', letterSpacing: '0.06em', marginBottom: 5 }}>Top risk</div>
              <p style={{ fontSize: 12, color: '#791F1F', margin: 0, lineHeight: 1.55 }}>{brief.risk}</p>
            </div>
            <div style={{ background: '#EAF3DE', borderRadius: 8, padding: '10px 12px' }}>
              <div style={{ fontSize: 10, fontWeight: 600, color: '#3B6D11', textTransform: 'uppercase', letterSpacing: '0.06em', marginBottom: 5 }}>60-day opportunity</div>
              <p style={{ fontSize: 12, color: '#27500A', margin: 0, lineHeight: 1.55 }}>{brief.opportunity}</p>
            </div>
            <div style={{ background: '#EEEDFE', borderRadius: 8, padding: '10px 12px' }}>
              <div style={{ fontSize: 10, fontWeight: 600, color: '#534AB7', textTransform: 'uppercase', letterSpacing: '0.06em', marginBottom: 5 }}>Competitive context</div>
              <p style={{ fontSize: 12, color: '#3C3489', margin: 0, lineHeight: 1.55 }}>{brief.competitive}</p>
            </div>
          </div>
        </div>

        {/* CTA */}
        <div style={{ textAlign: 'center' }}>
          <button
            onClick={() => navigate('/agent-readiness-audit')}
            style={{ fontSize: 13, color: '#fff', background: '#534AB7', border: 'none', borderRadius: 8, padding: '10px 24px', cursor: 'pointer', fontWeight: 500 }}
          >
            View full audit →
          </button>
          <p style={{ fontSize: 11, color: '#9CA3AF', marginTop: 8 }}>
            Generated by Arena · {date}
          </p>
        </div>
      </div>
    </div>
  );
}
